import type { ColumnIndexMapping } from './product-import.types';
import { findColumnIndex } from './product-import-row-utils';

export function getDefaultColumnIndexMapping(
  headers: ReadonlyMap<string, number>,
): ColumnIndexMapping {
  const find = (names: readonly string[]) => findColumnIndex(headers, names);
  return {
    productNameIdx: find([
      'nome prodotto',
      'nome prodotto fitosanitario',
      'nome formulato commerciale',
      'nome formulato commerciale o refluo zootecnico',
      'formulato commerciale',
      'product_name',
      'product name',
      'productname',
      'nome',
      'name',
      'fito',
      'prodotto',
      'articolo',
      'descrizione',
    ]),
    skuIdx: find(['sku', 'id', 'codice prodotto', 'codice articolo', 'product code', 'product id']),
    registrationNumberIdx: find([
      'numero registrazione',
      'n registrazione',
      'num registrazione',
      'registration number',
      'registrationNumber',
      'n. reg.',
      'n reg',
      'reg. n.',
    ]),
    categoryIdx: find(['categoria', 'category', 'tipo prodotto', 'product category']),
    supplierNameIdx: find([
      'ditta fornitrice',
      'fornitore',
      'supplier',
      'ditta',
      'ragione sociale fornitore',
    ]),
    quantityIdx: find([
      'quantita stock',
      'quantita fattura',
      'quantita acquistata',
      'quantità stock',
      'quantità fattura',
      'quantità acquistata',
      'quantita',
      'quantità',
      'quantity',
      'qty',
      'qta',
      'giacenza',
    ]),
    unitOfMeasureQuantityIdx: find([
      'unita di misura stock',
      'unita di misura',
      'unit_of_measure',
      'unit of measure',
      'unitofmeasure',
      'um',
      'u.m.',
      'u m',
      'unita',
      'unità',
      'udm',
      'uom',
    ]),
    priceIdx: find([
      'prezzo',
      'price',
      'prezzo unitario',
      'unit price',
      'costo unitario',
      'prezzo acquisto',
      'prezzo vendita',
    ]),
    unitOfMeasurePriceIdx: find([
      'unita di misura prezzo',
      'unita prezzo',
      'unit of measure price',
      'price unit',
      'udm prezzo',
      'uom price',
    ]),
    typeIdx: find(['tipo movimento', 'movement type', 'tipo', 'stock type', 'direzione']),
    ddtCodeIdx: find([
      'codice ddt',
      'ddt_code',
      'ddt code',
      'ddtcode',
      'ddt',
      'n ddt',
      'numero ddt',
      'n. ddt',
      'numero documento',
      'n documento',
      'codice',
    ]),
    ddtDateIdx: find([
      'data ddt',
      'data d.d.t.',
      'data d d t',
      'ddt date',
      'ddt_date',
      'dataddt',
      'ddtdata',
      'data documento',
      'data',
      'date',
    ]),
    invoiceCodeIdx: find([
      'n ft',
      'n. ft.',
      'n ft.',
      'numero fattura',
      'n fattura',
      'invoice number',
      'invoice_number',
      'codice fattura',
    ]),
    invoiceDateIdx: find([
      'data fattura',
      'data fatt',
      'data fatt.',
      'invoice date',
      'invoice_date',
      'data documento',
    ]),
    invoiceDueDateIdx: find([
      'scadenza fattura',
      'invoice due date',
      'invoice_due_date',
      'data scadenza',
      'scadenza',
    ]),
    initialStockQuantityIdx: find([
      'giacenza iniziale',
      'giacenza inizio',
      'stock iniziale',
      'rimanenza iniziale',
    ]),
  };
}
