import { Router } from 'express';
import { authRouter } from './auth.routes';
import { emailRouter } from './email.routes';
import { companyRouter } from './company.routes';
import { userOnCompanyRouter } from './user-on-company.routes';
import { settingsRouter } from './settings.routes';
import { qdcRouter } from './qdc.routes';
import { patentinoRouter } from './patentino.routes';
import { warehouseRouter } from './warehouse.routes';
import { productRouter } from './product.routes';
import { stockRouter } from './stock.routes';
import { fieldRouter } from './field.routes';
import { productionUnitRouter } from './production-unit.routes';
import { productionCycleRouter } from './production-cycle.routes';
import { jobRouter } from './job.routes';
import { userRouter } from './user.routes';
import { labelRouter } from './label.routes';
import { labelRefreshRouter } from './label-refresh.routes';
import { internalLabelRefreshRouter } from './internal-label-refresh.routes';
import { csvTreatmentsRouter } from './job-dataset.routes';
import { dosageAgentRouter } from './dosage-agent.routes';
import { vectorSearchRouter } from './vector-search.routes';
import { healthRouter } from './health.routes';
import { debugRouter } from './debug.routes';
import { toolRouter } from './tool.routes';
import { fileRouter } from './file.routes';
import { agentChatRouter } from './agent-chat.routes';
import { chatRouter } from './chat.routes';
import { machineRouter } from './machine.routes';
import { conformityCheckerRouter } from './conformity-checker.routes';
import { workspaceRouter } from './workspace.routes';
import { ruleRouter } from './rule.routes';
import { publicRuleRouter } from './public-rule.routes';
import { skillRouter } from './skill.routes';
import { publicSkillRouter } from './public-skill.routes';
import keepAliveRouter from './keep-alive.routes';
import { fieldNoteRouter } from './field-note.routes';
import { fieldNoteAgentRouter } from './field-note-agent.routes';
import { audioToTextRouter } from './audio-to-text.routes';
import { whatsappWebhookRouter } from './whatsapp-webhook.routes';
import { emailInboundRouter } from './email-inbound.routes';
import { jobVerificationAgentRouter } from './job-verification-agent.routes';
import { disciplinariRouter } from './disciplinari.routes';
import { scrapegraphRouter } from './scrapegraph.routes';
import { telegramAuthRouter } from './telegram-auth.routes';
import { googleAuthRouter } from './google-auth.routes';
import { onboardingRouter } from './onboarding.routes';
import { bdfRouter } from './bdf.routes';
import { adminRouter } from './admin.routes';
import { extractionRouter } from './extraction.routes';
import { notificationRouter } from './notification.routes';
import { mentionRouter } from './mention.routes';
import { businessPartnerRouter } from './business-partner.routes';
import { salesOrderRouter } from './sales-order.routes';
import { deliveryNoteRouter } from './delivery-note.routes';
import { proformaRouter } from './proforma.routes';
import { salesInvoiceRouter } from './sales-invoice.routes';
import { commercialRouter } from './commercial.routes';
import { extractionApiRouter } from './extraction-api.routes';

export const router = Router();

router.use('/', healthRouter);
router.use('/', toolRouter);
router.use('/files', fileRouter);
router.use('/debug', debugRouter);
router.use('/auth', authRouter);
router.use('/auth/telegram', telegramAuthRouter);
router.use('/auth/google', googleAuthRouter);
router.use('/email', emailRouter);
router.use('/companies', companyRouter);
router.use('/user-on-company', userOnCompanyRouter);
router.use('/settings', settingsRouter);
router.use('/qdc', qdcRouter);
router.use('/patentini', patentinoRouter);
router.use('/warehouses', warehouseRouter);
router.use('/products', productRouter);
router.use('/stocks', stockRouter);
router.use('/fields', fieldRouter);
router.use('/production-units', productionUnitRouter);
router.use('/production-units', productionCycleRouter);
router.use('/jobs', jobRouter);
router.use('/users', userRouter);
router.use('/internal', internalLabelRefreshRouter);
router.use('/labels', labelRefreshRouter);
router.use('/labels', labelRouter);
router.use('/csv-treatments', csvTreatmentsRouter);
router.use('/dosage-agent', dosageAgentRouter);
router.use('/vector-search', vectorSearchRouter);
router.use('/agent-chat', agentChatRouter);
router.use('/chats', chatRouter);
router.use('/machines', machineRouter);
router.use('/conformity-checker', conformityCheckerRouter);
router.use('/workspaces', workspaceRouter);
router.use('/', ruleRouter);
router.use('/', publicRuleRouter);
router.use('/', skillRouter);
router.use('/', publicSkillRouter);
router.use('/keep-alive', keepAliveRouter);
router.use('/field-notes', fieldNoteRouter);
router.use('/field-note-agent', fieldNoteAgentRouter);
router.use('/audio-to-text', audioToTextRouter);
router.use('/webhooks/whatsapp', whatsappWebhookRouter);
router.use('/webhooks/email', emailInboundRouter);
router.use('/job-verification-agent', jobVerificationAgentRouter);
router.use('/disciplinari', disciplinariRouter);
router.use('/scrapegraph', scrapegraphRouter);
router.use('/onboarding', onboardingRouter);
router.use('/bdf', bdfRouter);
router.use('/admin', adminRouter);
router.use('/extractions', extractionRouter);
router.use('/notifications', notificationRouter);
router.use('/mentions', mentionRouter);
router.use('/business-partners', businessPartnerRouter);
router.use('/orders', salesOrderRouter);
router.use('/ddt', deliveryNoteRouter);
router.use('/proforma', proformaRouter);
router.use('/sales-invoices', salesInvoiceRouter);
router.use('/commercial', commercialRouter);
router.use('/api/v1/extract', extractionApiRouter);
