-- CreateEnum
CREATE TYPE "DocumentCategory" AS ENUM ('DDT', 'DISCIPLINARE', 'FASCICOLO_AZIENDALE', 'FATTURA', 'MAGAZZINO', 'ETICHETTA', 'VISURA_AZIENDALE', 'NOTA', 'PIANO_COLTURALE', 'CERTIFICAZIONE', 'ALTRO');
