export const SECTION_KEYS = {
  modalita: ['modalita_applicazione', 'epoca_impiego', 'epoca_impiego_llm'] as const,
  magazzino: [
    'stock_in_warehouse',
    'stock_out',
    'total_stock_required_for_jobs',
    'ddt_date_is_ok',
    'ddt_date_conformity',
    'ddt_date_after_treatment',
  ] as const,
  malattie: [
    'malattie',
    'principio_attivo',
    'note_tecniche',
    'colture_target_fuori_periodo_di_produzione',
    'colture_target_fuori_periodo_di_produzione_llm',
  ] as const,
  fasce: [
    'fasce_di_rispetto_e_deriva',
    'fasce_di_rispetto_e_deriva_llm',
    'fasce_rispetto_acqua',
    'fasce_rispetto_colture',
  ] as const,
  conformita: [
    'ruleViolations',
    'ruleComplianceNotes',
    'disciplinare_info',
    'resistenze',
    'resistenze_llm',
  ] as const,
  pericolo: ['frasi_pericolo'] as const,
  dose: [
    'dose_minima',
    'dose_massima',
    'dose_minima_hl_job',
    'dose_massima_hl_job',
    'acqua_max',
    'waterHlJob',
    'acquaMaxJob',
    'n_max_applicazioni',
  ] as const,
} as const;

export const KNOWN_ALERT_KEYS: ReadonlySet<string> = new Set<string>([
  ...SECTION_KEYS.dose,
  ...SECTION_KEYS.modalita,
  ...SECTION_KEYS.magazzino,
  ...SECTION_KEYS.malattie,
  ...SECTION_KEYS.fasce,
  ...SECTION_KEYS.conformita,
  ...SECTION_KEYS.pericolo,
  'dose_um',
  'acqua_max_um',
  'acquaMaxJob_um',
  'stock_out_um',
  'stock_in_warehouse_um',
  'total_stock_required_for_jobs_um',
  'n_max_applicazioni_um',
  'excluded_product',
  'exclusion_reason',
]);
